export const TMDB_COUNTRIES = [
  { code: 'CN', label: '中国大陆' },
  { code: 'HK', label: '中国香港' },
  { code: 'TW', label: '中国台湾' },
  { code: 'SG', label: '新加坡' },
  { code: 'JP', label: '日本' },
  { code: 'KR', label: '韩国' },
  { code: 'KP', label: '朝鲜' },
  { code: 'US', label: '美国' },
  { code: 'GB', label: '英国' },
  { code: 'CA', label: '加拿大' },
  { code: 'AU', label: '澳大利亚' },
  { code: 'FR', label: '法国' },
  { code: 'DE', label: '德国' },
  { code: 'IT', label: '意大利' },
  { code: 'ES', label: '西班牙' },
  { code: 'RU', label: '俄罗斯' },
  { code: 'IN', label: '印度' },
  { code: 'TH', label: '泰国' },
  { code: 'MY', label: '马来西亚' },
  { code: 'ID', label: '印度尼西亚' },
  { code: 'PH', label: '菲律宾' },
  { code: 'VN', label: '越南' },
  { code: 'BR', label: '巴西' },
  { code: 'MX', label: '墨西哥' },
  { code: 'AR', label: '阿根廷' },
  { code: 'SE', label: '瑞典' },
  { code: 'NO', label: '挪威' },
  { code: 'DK', label: '丹麦' },
  { code: 'FI', label: '芬兰' },
  { code: 'NL', label: '荷兰' },
  { code: 'BE', label: '比利时' },
  { code: 'CH', label: '瑞士' },
  { code: 'PL', label: '波兰' },
  { code: 'TR', label: '土耳其' },
  { code: 'IR', label: '伊朗' },
  { code: 'ZA', label: '南非' }
]

export const TMDB_MOVIE_GENRES = [
  { id: 28, label: '动作' },
  { id: 12, label: '冒险' },
  { id: 16, label: '动画' },
  { id: 35, label: '喜剧' },
  { id: 80, label: '犯罪' },
  { id: 99, label: '纪录片' },
  { id: 18, label: '剧情' },
  { id: 10751, label: '家庭' },
  { id: 14, label: '奇幻' },
  { id: 36, label: '历史' },
  { id: 27, label: '恐怖' },
  { id: 10402, label: '音乐' },
  { id: 9648, label: '悬疑' },
  { id: 10749, label: '爱情' },
  { id: 878, label: '科幻' },
  { id: 10770, label: '电视电影' },
  { id: 53, label: '惊悚' },
  { id: 10752, label: '战争' },
  { id: 37, label: '西部' }
]

export const TMDB_TV_GENRES = [
  { id: 10759, label: '动作冒险' },
  { id: 16, label: '动漫' },
  { id: 35, label: '喜剧' },
  { id: 80, label: '犯罪' },
  { id: 99, label: '纪录片' },
  { id: 18, label: '剧情' },
  { id: 10751, label: '家庭' },
  { id: 10762, label: '儿童' },
  { id: 9648, label: '悬疑' },
  { id: 10763, label: '新闻' },
  { id: 10764, label: '真人秀' },
  { id: 10765, label: '科幻奇幻' },
  { id: 10766, label: '肥皂剧' },
  { id: 10767, label: '脱口秀' },
  { id: 10768, label: '战争政治' },
  { id: 37, label: '西部' }
]
